apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "musescore-reader.frontend.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "musescore-reader.name" . }}
    app.kubernetes.io/component: frontend
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  rules:
    - host: {{ .Values.frontend.ingress.domain }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ include "musescore-reader.backend.fullname" . }}
                port:
                  name: http
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "musescore-reader.frontend.fullname" . }}
                port:
                  name: http
