backend:
  version: "0.4.4"
  replicas: 1
  corsAllowedOrigins: ""
  superadminUsername: "superadmin"
  musescoreDirectOggStems: true
  ingress:
    domain: "fumen-api.lehang.art"

frontend:
  version: "0.4.5"
  apiBaseUrl: ""
  ingress:
    domain: "fumen.lehang.art"
